### ISSUE TITLE
how to get views count?

### ISSUE THREAD

**Issue by altaf2892** [a-tolstykh/TextViewPagination#1]
i have used this example but i also need views count ? so can u tell me how to get count?

**Comment by a-tolstykh** [comment]
What count do you mean?

**Comment by altaf2892** [comment]
i mean how many views .... got it ?? still not?  ok
i want to get count of pages example how many pages are there right sides that user can swipe

**Comment by a-tolstykh** [comment]
You can iterate the complete text and calculate the displayed text for each page. I don't see the better solution since you don't know the count before you actually layout it...
